version: "3"

tasks:
  dev:
    desc: "Starts both Server (task dev) and WebApp (npm run dev) in parallel"
    cmds:
      - task: clone-init
      - task: dev-deps
    silent: true

  dev-deps:
    deps:
      - server-dev
      - webapp-dev
      - "{{OS}}:open"
    parallel: true
    internal: true

  clone-init:
    cmds:
      - cmd: "git clone git@github.com:OICAR-07-ePrometna/ePrometna_Server.git"
      - cmd: "git clone git@github.com:OICAR-07-ePrometna/ePrometna_WebApp.git"
    ignore_error: true
    internal: true
    silent: true

  server-dev:
    desc: "Runs 'task dev' in the ePrometna_Server directory"
    dir: ./ePrometna_Server
    deps:
      - task: "{{OS}}:server-setup-env"
      - task: server-install-dep
    parallel: true
    cmds:
      - cmd: "task dev"
    signal: SIGINT

  linux:server-setup-env:
    cmd:
      task: server-setup-env
    internal: true

  darwin:server-setup-env:
    cmd:
      task: server-setup-env
    internal: true

  server-setup-env:
    dir: ./ePrometna_Server
    cmd: "[ -f '.env' ] || cp env.example .env"
    internal: true

  windows:server-setup-env:
    cmd: "if (-not (Test-Path -Path '.env' -PathType Leaf)) { Copy-Item -Path 'env.example' -Destination '.env' }"
    internal: true

  webapp-dev:
    desc: "Runs 'npm run dev' in the project2 directory"
    dir: ./ePrometna_WebApp
    deps:
      - webapp-install-dep
    cmds:
      - npm run dev
    signal: SIGINT

  webapp-install-dep:
    dir: ./ePrometna_WebApp
    cmd: npm install
    internal: true

  server-install-dep:
    dir: ./ePrometna_Server/
    cmds:
      - cmd: "go install github.com/air-verse/air@latest"
      - cmd: "go install github.com/swaggo/swag/cmd/swag@latest"
    internal: true

  linux:open:
    platforms: [linux]
    cmd: xdg-open http://localhost:3000
    internal: true

  darwin:open:
    platforms: [darwin]
    cmd: open http://localhost:3000
    internal: true

  windows:open:
    platforms: [windows]
    cmd: start http://localhost:3000
    internal: true
